---
 - name: start,restart,stop and permanent the services
   hosts: prakash41
   tasks:
   - name: start and permanent the httpd service
     service: name=httpd state=started enabled=yes

   - name: restart the httpd service
     service: name=httpd state=restarted

   - name: stop the httpd service
     service: name=httpd state=stopped enabled=no
